# Generated by Django 4.1.9 on 2023-06-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("image_src", models.CharField(max_length=200)),
                ("image_alt", models.CharField(max_length=200)),
                ("author_name", models.CharField(max_length=200)),
                ("author_image_src", models.CharField(max_length=200)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("original_article", models.JSONField(null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="laimpostapp.article",
                    ),
                ),
            ],
        ),
    ]
