# Generated by Django 4.1.9 on 2023-06-02 22:57

from django.db import migrations, models
import django.db.models.deletion
import laimpostapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=laimpostapp.models.gen_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image_src', models.CharField(max_length=200)),
                ('image_alt', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('author_image_src', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=laimpostapp.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_image_src', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='laimpostapp.article')),
            ],
        ),
    ]
