# Generated by Django 4.1.9 on 2023-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laimpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='original_article',
            field=models.JSONField(null=True),
        ),
    ]
